ingress:
  host: a5b932b222704417ba8c156b8398fdbb-1366802763.us-east-1.elb.amazonaws.com
mysql:
  label: mysql
  image: mysql:latest
  replicas: 1
  ports:
    port: 3306
    targetPort: 3306
  host: a5b932b222704417ba8c156b8398fdbb-1366802763.us-east-1.elb.amazonaws.com
backend:
  replicas: 2
  label: backend
  image:
    repository: 869935092862.dkr.ecr.us-east-1.amazonaws.com/backend
    tag: latest
  ports:
    containerPort: 80
  config:
    FLASK_RUN_HOST: "0.0.0.0"
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
secrets: 
  MYSQL_DATABASE: kartikdatabase
  MYSQL_ROOT_PASSWORD: password
  MYSQL_USER: kartikuser
  MYSQL_PASSWORD: password
