ingress:
  host: ae17af75262a649ef97d437b2ae80270-525036724.us-east-1.elb.amazonaws.com
mysql:
  label: mysql
  image: mysql:latest
  replicas: 1
  ports:
    port: 3306
    targetPort: 3306
  host: ae17af75262a649ef97d437b2ae80270-525036724.us-east-1.elb.amazonaws.com
backend:
  replicas: 2
  label: backend
  image:
    repository: 015800953128.dkr.ecr.us-east-1.amazonaws.com/backend
    tag: ""
  ports:
    containerPort: 80
  config:
    FLASK_RUN_HOST: "0.0.0.0"
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
secrets: 
  MYSQL_DATABASE: kartikdatabase
  MYSQL_ROOT_PASSWORD: password
  MYSQL_USER: kartikuser
  MYSQL_PASSWORD: password
  # AWS_ACCESS_KEY_ID: 
  # AWS_SECRET_ACCESS_KEY: 
