ingress:
  host: a5b932b222704417ba8c156b8398fdbb-1366802763.us-east-1.elb.amazonaws.com
backend:
  replicas: 2
  image:
    repository: 869935092862.dkr.ecr.us-east-1.amazonaws.com/backend
    tag: latest
  config:
    FLASK_RUN_HOST: "0.0.0.0"
  service:
    type: ClusterIP
    port: 5000
secrets: 
  MYSQL_DATABASE: kartikdatabase
  MYSQL_ROOT_PASSWORD: password
  MYSQL_USER: kartikuser
  MYSQL_PASSWORD: password
