apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  labels:
    app: myapp
data:
  APP_ENV: "{{ .Values.config.appEnv }}"
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  REDIS_HOST: "{{ .Values.config.redisHost }}"
