# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: mysql-backup-cronjob
# spec:
#   schedule: "*/2 * * * *"  # Runs every 6 hours
#   jobTemplate:
#     spec:
#       serviceAccountName: s3-backup-sa
#       template:
#         spec:
#           containers:
#             - name: s3-backup-sa
#               image: 911806762272.dkr.ecr.us-east-1.amazonaws.com/mysql-aws:latest
#               command:
#                 - /bin/bash
#                 - -c
#                 - backup.sh
#             env:
#               - name: MYSQL_ROOT_PASSWORD
#                 valueFrom:
#                   secretKeyRef:
#                     name: myapp-secret
#                     key: MYSQL_ROOT_PASSWORD
#               - name: AWS_ACCESS_KEY_ID
#                 valueFrom:
#                   secretKeyRef:
#                     name: myapp-secret
#                     key: AWS_ACCESS_KEY_ID
#               - name: AWS_SECRET_ACCESS_KEY
#                 valueFrom:
#                   secretKeyRef:
#                     name: myapp-secret
#                     key: AWS_SECRET_ACCESS_KEY
#               - name: AWS_DEFAULT_REGION
#                 value: "us-east-1"  # Change to your AWS region
#             volumeMounts:
#               - name: backup-storage
#                 mountPath: /backup
#           restartPolicy: OnFailure
#           volumes:
#           - name: backup-storage
#             persistentVolumeClaim:
#               claimName: backup-storage
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup-cronjob
spec:
  schedule: "*/4 * * * *"  # Runs every 2 minutes (change as needed)
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: s3-backup-sa
          containers:
            - name: mysql-backup
              image: 911806762272.dkr.ecr.us-east-1.amazonaws.com/mysql-aws:latest
# we can change  - /backup/backup.sh to -backup.sh or else we can also remove it because we have already given the command to run backup.sh in Dockerfile 
              command:
                - /bin/sh
                - -c
                - /backup/backup.sh
              env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: myapp-secret
                      key: MYSQL_ROOT_PASSWORD
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: myapp-secret
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: myapp-secret
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_DEFAULT_REGION
                  value: "us-east-1"  # Change to your AWS region
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: backup-storage

