apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ include "backend-label" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend-label" . }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.ports.containerPort }}
          env:
            - name: FLASK_RUN_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: FLASK_RUN_HOST
