apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  clusterIP: None  # Headless Service for StatefulSet
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.ports.port }}
      targetPort: {{ .Values.mysql.ports.targetport }}

