apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
spec:
  capacity:
    storage: 1Gi  
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: manual
  hostPath:
    path: "/mnt/backup-data"  # Ensure this directory exists on your host

