apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: backend-eks  # Replace with your actual Helm release name
    meta.helm.sh/release-namespace: default  # Replace with your actual namespace
spec:
  capacity:
    storage: 1Gi  
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: manual
  hostPath:
    path: "/mnt/backup-data"  # Ensure this directory exists on your host


