apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  labels:
    app: myapp
type: Opaque
data:
  MYSQL_USER: {{ .Values.secrets.MYSQL_USER | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.MYSQL_PASSWORD | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.secrets.MYSQL_DATABASE | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.MYSQL_ROOT_PASSWORD | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_SECRET_ACCESS_KEY | b64enc | quote }}
